In [ ]:
# DATA SCIENCE LIBRARY -- PANDAS
import numpy as np
import pandas as pd

In [ ]:
# numpy --> array()
arr = np.array([10,20,30,40])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40]

In [ ]:
# Pandas Series
# Series is 1D Labelled Array

s = pd.Series([10,20,30,40])
print(type(s))
print(s)
print(s.shape)

<class 'pandas.core.series.Series'>
0    10
1    20
2    30
3    40
dtype: int64
(4,)

In [ ]:
# in numpy array we can not store mixed data types
arr = np.array([123,'John',4500.32,True])
print(arr)

['123' 'John' '4500.32' 'True']

In [ ]:
s = pd.Series([123,'John',4500.32,True])
print(s.values)

[123 'John' 4500.32 True]

In [ ]:
s = pd.Series([123,'John',4500.32,True],index=['id','name','sal','status'])
print(s)
print(s['sal'])
print(s.iloc[3])       # if you want to print the Data Value By Using An Index Number use iloc [index location]
# built-in function  get()
print(s.get('name'))

#  123   'John'    4500.32   True
#  0       1         2        3
#  id    name        sal     status

# Series is like a Dictionary + Array combo

id            123
name         John
sal       4500.32
status       True
dtype: object
4500.32
True
John

In [ ]:
# Indexing Slicing And using For Loop
s = pd.Series([123,'John',4500.32,True],index=['id','name','sal','status'])
print(s)

#  123   'John'    4500.32   True
#  0       1         2        3
#  id    name        sal     status

# Indexing in Series can be done by using [] , iloc[] or loc[]
print('\nIndexing In Series')
print(s['sal'])        # use [] for labels
print(s.loc['name'])   # use loc for labels
print(s.iloc[3])       # use iloc for indexNumbers

print('\nSlicing In Series')
print(s[0:3])                 # 3 will be excluded --> stopIndex
print(s['name':'status'])    # if performing slicing using labels , the end label is included

print('\nPrinting Specific Information')
print(s[['id','name','status']])  # s[['labelname','labelname']]
print(s[['id','name','status']].values)

id            123
name         John
sal       4500.32
status       True
dtype: object

Indexing In Series
4500.32
John
True

Slicing In Series
id          123
name       John
sal     4500.32
dtype: object
name         John
sal       4500.32
status       True
dtype: object

Printing Specific Information
id         123
name      John
status    True
dtype: object
[123 'John' True]

In [ ]:
# Using For Loop
for i in s:
    print(i)

123
John
4500.32
True

In [ ]:
for k,v in s.items():
    print(k,v)

id 123
name John
sal 4500.32
status True

In [ ]:
# Pandas DataFrame

# It's a 2D array

# it is used to display the information in a tabular fashion

data = {

    'name' : ['John' , 'Smith' , 'Alex' , 'Mathews'],

    'dept' : ['IT', 'Marketing', 'Sales', 'Finance'],

    'salary' : [7800 , 6700 , 5500 , 8000],

    'city' : ['KL' , 'Klang' , 'Melacca' , 'Johor']

}

print(data)

{'name': ['John', 'Smith', 'Alex', 'Mathews'], 'dept': ['IT', 'Marketing', 'Sales', 'Finance'], 'salary': [7800, 6700, 5500, 8000], 'city': ['KL', 'Klang', 'Melacca', 'Johor']}

In [ ]:
df = pd.DataFrame(data)
df

      name       dept  salary     city
0     John         IT    7800       KL
1    Smith  Marketing    6700    Klang
2     Alex      Sales    5500  Melacca
3  Mathews    Finance    8000    Johor

In [ ]:
print(df.shape)

(4, 4)

In [ ]:
data = {
    'Calories' : [420,380,560],
    'Duration' : [56,30,75]
}
df = pd.DataFrame(data,index=['Day1','Day2','Day3'])
df

      Calories  Duration
Day1       420        56
Day2       380        30
Day3       560        75

In [ ]:
df['Calories']

Day1    420
Day2    380
Day3    560
Name: Calories, dtype: int64

In [ ]:
print(df['Calories'].values)

[420 380 560]

In [ ]:
df.loc['Day1']

Calories    420
Duration     56
Name: Day1, dtype: int64

In [ ]:
df.loc[['Day1','Day3']]

      Calories  Duration
Day1       420        56
Day3       560        75

In [ ]:
df[df['Duration'] > 50]

      Calories  Duration
Day1       420        56
Day3       560        75